equal = "="
name=input("Enter your name: ")
x=name.center(30)
YOB=int(input("Enter your year of birth: "))
place=input("Enter your city: ")
hobby=input("Enter your hobby: ")
print(equal*45)
print(x)
print(equal*45)
print(f"Name: {name}")
print(f"Age: {2025-YOB} (born in {YOB})")
print(f"Location: {place}")
print(f"Hobby: {hobby}")
print(f"{name} is a {2025-YOB}-year-old {hobby} enthusiast from {place}")
print(equal*45)